### ISSUE TITLE
Default windows buttons are conflicting with the extension's buttons

### ISSUE THREAD

**Issue by ItzNinjaHo** [HealKnix/macos-titlebar-for-windows#2]
Second Issue..  If i open a new window of vscode the buttons will be fine but if i drag a file to open the file as a new window the buttons on the new window opened from the main vscode window will be like this:
<img width="90" alt="Screenshot 2024-07-05 204055" src="https://github.com/HealKnix/macos-titlebar-for-windows/assets/110479061/2215a566-03c6-451f-a4e7-e6090fea1e0c">
_( I love your extension by the way )_

**Comment by HealKnix** [comment]
Thanks for the kind words =)
Following your words, I tried to reproduce this bug, but nothing worked. To be honest, I have no idea what it could be related to.
My extension only changes styles for classes using the `Apc Customize UI++` extension, so I can only attribute it to that.

**Comment by ItzNinjaHo** [comment]
No problem. Im just opening new windows of VSCode and it seems to show the buttons perfectly!
